'use client'
import { SignedContent } from '@gind-ia-platform/generic-components';
import { AppBar, Toolbar } from '@mui/material';
import './global.css';
import { Chat, Home } from '@mui/icons-material';
import Link from 'next/link';

// export const metadata = {
//   title: 'Welcome to gind-ia-server',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     <body>
      <SignedContent publicContent={<p>public content</p>} links={<>
              <Link  href="/" style={{margin:"5pt"}}>
                <Home color="inherit"></Home>Home
              </Link>
               <Link  href="/chat" style={{margin:"5pt"}}>
                <Chat color="inherit"/> Chat
              </Link>
      </>}>
            {/* <AppBar position="relative" color="transparent" variant="outlined">
          <Toolbar>
          <Link  href="/chat">
                <Chat/> Chat
              </Link>
          </Toolbar>

            </AppBar> */}
            {children}
      </SignedContent>
      </body>
    </html>
  );
}
