services:
  # ollama:
  #   image: "ollama/ollama"
  #   volumes:
  #     - ./ollama:/root/.ollama
  #   ports:
  #     - 11434:11434
  mongodb:
    image: "mongodb/mongodb-community-server"
    volumes:
      - ./gind-ia-database:/data/db
    ports:
      - 27017:27017

  gind-ia-server:
    image: "gind-ia-server:main"
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      # - ollama
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
